<Style name="Clade_names">
  <Rule>
    <Filter>[zoomview] = 0</Filter>
    &maxscale_zoom1
    &minscale_zoom1
    <TextSymbolizer size="12" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="10">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 0</Filter>
    &maxscale_zoom2
    &minscale_zoom2
    <TextSymbolizer size="15" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="12">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 0</Filter>
    &maxscale_zoom3
    &minscale_zoom3
    <TextSymbolizer size="25" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="20">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 1</Filter>
    &maxscale_zoom2
    &minscale_zoom2
    <TextSymbolizer size="12" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="10">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 1</Filter>
    &maxscale_zoom3
    &minscale_zoom3
    <TextSymbolizer size="15" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="12">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 1</Filter>
    &maxscale_zoom4
    &minscale_zoom4
    <TextSymbolizer size="25" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="20">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 2</Filter>
    &maxscale_zoom3
    &minscale_zoom3
    <TextSymbolizer size="12" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="10">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 2</Filter>
    &maxscale_zoom4
    &minscale_zoom4
    <TextSymbolizer size="15" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="12">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 2</Filter>
    &maxscale_zoom5
    &minscale_zoom5
    <TextSymbolizer size="25" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="20">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 3</Filter>
    &maxscale_zoom4
    &minscale_zoom4
    <TextSymbolizer size="12" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="10">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 3</Filter>
    &maxscale_zoom5
    &minscale_zoom5
    <TextSymbolizer size="15" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="12">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 3</Filter>
    &maxscale_zoom6
    &minscale_zoom6
    <TextSymbolizer size="25" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="20">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 4</Filter>
    &maxscale_zoom5
    &minscale_zoom5
    <TextSymbolizer size="12" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="10">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 4</Filter>
    &maxscale_zoom6
    &minscale_zoom6
    <TextSymbolizer size="15" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="12">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 4</Filter>
    &maxscale_zoom7
    &minscale_zoom7
    <TextSymbolizer size="25" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="20">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 5</Filter>
    &maxscale_zoom6
    &minscale_zoom6
    <TextSymbolizer size="12" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="10">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 5</Filter>
    &maxscale_zoom7
    &minscale_zoom7
    <TextSymbolizer size="15" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="12">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 5</Filter>
    &maxscale_zoom8
    &minscale_zoom8
    <TextSymbolizer size="25" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="20">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 6</Filter>
    &maxscale_zoom7
    &minscale_zoom7
    <TextSymbolizer size="12" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="10">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 6</Filter>
    &maxscale_zoom8
    &minscale_zoom8
    <TextSymbolizer size="15" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="12">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 6</Filter>
    &maxscale_zoom9
    &minscale_zoom9
    <TextSymbolizer size="25" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="20">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 7</Filter>
    &maxscale_zoom8
    &minscale_zoom8
    <TextSymbolizer size="12" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="10">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 7</Filter>
    &maxscale_zoom9
    &minscale_zoom9
    <TextSymbolizer size="15" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="12">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 7</Filter>
    &maxscale_zoom10
    &minscale_zoom10
    <TextSymbolizer size="25" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="20">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 8</Filter>
    &maxscale_zoom9
    &minscale_zoom9
    <TextSymbolizer size="12" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="10">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 8</Filter>
    &maxscale_zoom10
    &minscale_zoom10
    <TextSymbolizer size="15" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="12">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 8</Filter>
    &maxscale_zoom11
    &minscale_zoom11
    <TextSymbolizer size="25" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="20">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 9</Filter>
    &maxscale_zoom10
    &minscale_zoom10
    <TextSymbolizer size="12" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="10">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 9</Filter>
    &maxscale_zoom11
    &minscale_zoom11
    <TextSymbolizer size="15" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="12">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 9</Filter>
    &maxscale_zoom12
    &minscale_zoom12
    <TextSymbolizer size="25" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="20">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 10</Filter>
    &maxscale_zoom11
    &minscale_zoom11
    <TextSymbolizer size="12" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="10">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 10</Filter>
    &maxscale_zoom12
    &minscale_zoom12
    <TextSymbolizer size="15" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="12">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 10</Filter>
    &maxscale_zoom13
    &minscale_zoom13
    <TextSymbolizer size="25" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="20">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 11</Filter>
    &maxscale_zoom12
    &minscale_zoom12
    <TextSymbolizer size="12" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="10">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 11</Filter>
    &maxscale_zoom13
    &minscale_zoom13
    <TextSymbolizer size="15" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="12">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 11</Filter>
    &maxscale_zoom14
    &minscale_zoom14
    <TextSymbolizer size="25" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="20">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 12</Filter>
    &maxscale_zoom13
    &minscale_zoom13
    <TextSymbolizer size="12" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="10">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 12</Filter>
    &maxscale_zoom14
    &minscale_zoom14
    <TextSymbolizer size="15" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="12">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 12</Filter>
    &maxscale_zoom15
    &minscale_zoom15
    <TextSymbolizer size="25" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="20">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 13</Filter>
    &maxscale_zoom14
    &minscale_zoom14
    <TextSymbolizer size="12" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="10">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 13</Filter>
    &maxscale_zoom15
    &minscale_zoom15
    <TextSymbolizer size="15" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="12">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 13</Filter>
    &maxscale_zoom16
    &minscale_zoom16
    <TextSymbolizer size="25" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="20">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 14</Filter>
    &maxscale_zoom15
    &minscale_zoom15
    <TextSymbolizer size="12" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="10">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 14</Filter>
    &maxscale_zoom16
    &minscale_zoom16
    <TextSymbolizer size="15" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="12">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 14</Filter>
    &maxscale_zoom17
    &minscale_zoom17
    <TextSymbolizer size="25" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="20">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 15</Filter>
    &maxscale_zoom16
    &minscale_zoom16
    <TextSymbolizer size="12" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="10">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 15</Filter>
    &maxscale_zoom17
    &minscale_zoom17
    <TextSymbolizer size="15" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="12">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 15</Filter>
    &maxscale_zoom18
    &minscale_zoom18
    <TextSymbolizer size="25" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="20">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 16</Filter>
    &maxscale_zoom17
    &minscale_zoom17
    <TextSymbolizer size="12" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="10">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 16</Filter>
    &maxscale_zoom18
    &minscale_zoom18
    <TextSymbolizer size="15" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="12">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 16</Filter>
    &maxscale_zoom19
    &minscale_zoom19
    <TextSymbolizer size="25" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="20">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 17</Filter>
    &maxscale_zoom18
    &minscale_zoom18
    <TextSymbolizer size="12" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="10">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 17</Filter>
    &maxscale_zoom19
    &minscale_zoom19
    <TextSymbolizer size="15" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="12">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 17</Filter>
    &maxscale_zoom20
    &minscale_zoom20
    <TextSymbolizer size="25" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="20">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 18</Filter>
    &maxscale_zoom19
    &minscale_zoom19
    <TextSymbolizer size="12" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="10">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 18</Filter>
    &maxscale_zoom20
    &minscale_zoom20
    <TextSymbolizer size="15" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="12">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 18</Filter>
    &maxscale_zoom21
    &minscale_zoom21
    <TextSymbolizer size="25" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="20">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 19</Filter>
    &maxscale_zoom20
    &minscale_zoom20
    <TextSymbolizer size="12" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="10">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 19</Filter>
    &maxscale_zoom21
    &minscale_zoom21
    <TextSymbolizer size="15" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="12">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 19</Filter>
    &maxscale_zoom22
    &minscale_zoom22
    <TextSymbolizer size="25" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="20">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 20</Filter>
    &maxscale_zoom21
    &minscale_zoom21
    <TextSymbolizer size="12" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="10">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 20</Filter>
    &maxscale_zoom22
    &minscale_zoom22
    <TextSymbolizer size="15" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="12">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 20</Filter>
    &maxscale_zoom23
    &minscale_zoom23
    <TextSymbolizer size="25" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="20">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 21</Filter>
    &maxscale_zoom22
    &minscale_zoom22
    <TextSymbolizer size="12" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="10">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 21</Filter>
    &maxscale_zoom23
    &minscale_zoom23
    <TextSymbolizer size="15" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="12">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 21</Filter>
    &maxscale_zoom24
    &minscale_zoom24
    <TextSymbolizer size="25" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="20">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 22</Filter>
    &maxscale_zoom23
    &minscale_zoom23
    <TextSymbolizer size="12" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="10">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 22</Filter>
    &maxscale_zoom24
    &minscale_zoom24
    <TextSymbolizer size="15" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="12">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 22</Filter>
    &maxscale_zoom25
    &minscale_zoom25
    <TextSymbolizer size="25" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="20">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 23</Filter>
    &maxscale_zoom24
    &minscale_zoom24
    <TextSymbolizer size="12" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="10">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 23</Filter>
    &maxscale_zoom25
    &minscale_zoom25
    <TextSymbolizer size="15" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="12">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 23</Filter>
    &maxscale_zoom26
    &minscale_zoom26
    <TextSymbolizer size="25" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="20">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 24</Filter>
    &maxscale_zoom25
    &minscale_zoom25
    <TextSymbolizer size="12" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="10">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 24</Filter>
    &maxscale_zoom26
    &minscale_zoom26
    <TextSymbolizer size="15" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="12">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 24</Filter>
    &maxscale_zoom27
    &minscale_zoom27
    <TextSymbolizer size="25" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="20">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 25</Filter>
    &maxscale_zoom26
    &minscale_zoom26
    <TextSymbolizer size="12" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="10">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 25</Filter>
    &maxscale_zoom27
    &minscale_zoom27
    <TextSymbolizer size="15" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="12">[common_name]</Format></TextSymbolizer>
  </Rule>
  <Rule>
    <Filter>[zoomview] = 25</Filter>
    &maxscale_zoom28
    &minscale_zoom28
    <TextSymbolizer size="25" fill="white" face-name="Sinkin Sans 400 Regular" halo-fill="#000000" halo-radius="0.5" halo-rasterizer="full" >[sci_name] + "\n" + <Format size="20">[common_name]</Format></TextSymbolizer>
  </Rule>
</Style>
