<!ENTITY % settings SYSTEM "settings.xml.inc">
%settings;
<!ENTITY datasource-settings SYSTEM "datasource-settings.xml.inc">
<!ENTITY fontset-settings SYSTEM "fontset-settings.xml.inc">
<!ENTITY srs900913 "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +no_defs +over">
<!ENTITY srsmercator "+proj=merc +datum=WGS84 +over">
<!ENTITY srs4326 "+init=epsg:4326">
<!ENTITY % layers SYSTEM "layers.xml.inc">
%layers;

<!ENTITY maxscale_zoom0 "<MaxScaleDenominator>250000000000</MaxScaleDenominator>">
<!ENTITY maxscale_zoom1 "<MaxScaleDenominator>500000000</MaxScaleDenominator>">
<!ENTITY minscale_zoom1 "<MinScaleDenominator>200000000</MinScaleDenominator>">
<!ENTITY maxscale_zoom2 "<MaxScaleDenominator>200000000</MaxScaleDenominator>">
<!ENTITY minscale_zoom2 "<MinScaleDenominator>100000000</MinScaleDenominator>">
<!ENTITY maxscale_zoom3 "<MaxScaleDenominator>100000000</MaxScaleDenominator>">
<!ENTITY minscale_zoom3 "<MinScaleDenominator>50000000</MinScaleDenominator>">
<!ENTITY maxscale_zoom4 "<MaxScaleDenominator>50000000</MaxScaleDenominator>">
<!ENTITY minscale_zoom4 "<MinScaleDenominator>25000000</MinScaleDenominator>">
<!ENTITY maxscale_zoom5 "<MaxScaleDenominator>25000000</MaxScaleDenominator>">
<!ENTITY minscale_zoom5 "<MinScaleDenominator>12500000</MinScaleDenominator>">
<!ENTITY maxscale_zoom6 "<MaxScaleDenominator>12500000</MaxScaleDenominator>">
<!ENTITY minscale_zoom6 "<MinScaleDenominator>6500000</MinScaleDenominator>">
<!ENTITY maxscale_zoom7 "<MaxScaleDenominator>6500000</MaxScaleDenominator>">
<!ENTITY minscale_zoom7 "<MinScaleDenominator>3000000</MinScaleDenominator>">
<!ENTITY maxscale_zoom8 "<MaxScaleDenominator>3000000</MaxScaleDenominator>">
<!ENTITY minscale_zoom8 "<MinScaleDenominator>1500000</MinScaleDenominator>">
<!ENTITY maxscale_zoom9 "<MaxScaleDenominator>1500000</MaxScaleDenominator>">
<!ENTITY minscale_zoom9 "<MinScaleDenominator>750000</MinScaleDenominator>">
<!ENTITY maxscale_zoom10 "<MaxScaleDenominator>750000</MaxScaleDenominator>">
<!ENTITY minscale_zoom10 "<MinScaleDenominator>400000</MinScaleDenominator>">
<!ENTITY maxscale_zoom11 "<MaxScaleDenominator>400000</MaxScaleDenominator>">
<!ENTITY minscale_zoom11 "<MinScaleDenominator>200000</MinScaleDenominator>">
<!ENTITY maxscale_zoom12 "<MaxScaleDenominator>200000</MaxScaleDenominator>">
<!ENTITY minscale_zoom12 "<MinScaleDenominator>100000</MinScaleDenominator>">
<!ENTITY maxscale_zoom13 "<MaxScaleDenominator>100000</MaxScaleDenominator>">
<!ENTITY minscale_zoom13 "<MinScaleDenominator>50000</MinScaleDenominator>">
<!ENTITY maxscale_zoom14 "<MaxScaleDenominator>50000</MaxScaleDenominator>">
<!ENTITY minscale_zoom14 "<MinScaleDenominator>25000</MinScaleDenominator>">
<!ENTITY maxscale_zoom15 "<MaxScaleDenominator>25000</MaxScaleDenominator>">
<!ENTITY minscale_zoom15 "<MinScaleDenominator>12500</MinScaleDenominator>">
<!ENTITY maxscale_zoom16 "<MaxScaleDenominator>12500</MaxScaleDenominator>">
<!ENTITY minscale_zoom16 "<MinScaleDenominator>5000</MinScaleDenominator>">
<!ENTITY maxscale_zoom17 "<MaxScaleDenominator>5000</MaxScaleDenominator>">
<!ENTITY minscale_zoom17 "<MinScaleDenominator>2500</MinScaleDenominator>">
<!ENTITY maxscale_zoom18 "<MaxScaleDenominator>2500</MaxScaleDenominator>">
<!ENTITY minscale_zoom18 "<MinScaleDenominator>1250</MinScaleDenominator>">
<!ENTITY maxscale_zoom19 "<MaxScaleDenominator>1250</MaxScaleDenominator>">
<!ENTITY minscale_zoom19 "<MinScaleDenominator>650</MinScaleDenominator>">
<!ENTITY maxscale_zoom20 "<MaxScaleDenominator>650</MaxScaleDenominator>">
<!ENTITY minscale_zoom20 "<MinScaleDenominator>380</MinScaleDenominator>">
<!ENTITY maxscale_zoom21 "<MaxScaleDenominator>380</MaxScaleDenominator>">
<!ENTITY minscale_zoom21 "<MinScaleDenominator>190</MinScaleDenominator>">
<!ENTITY maxscale_zoom22 "<MaxScaleDenominator>190</MaxScaleDenominator>">
<!ENTITY minscale_zoom22 "<MinScaleDenominator>100</MinScaleDenominator>">
<!ENTITY maxscale_zoom23 "<MaxScaleDenominator>100</MaxScaleDenominator>">
<!ENTITY minscale_zoom23 "<MinScaleDenominator>50</MinScaleDenominator>">
<!ENTITY maxscale_zoom24 "<MaxScaleDenominator>50</MaxScaleDenominator>">
<!ENTITY minscale_zoom24 "<MinScaleDenominator>25</MinScaleDenominator>">
<!ENTITY maxscale_zoom25 "<MaxScaleDenominator>25</MaxScaleDenominator>">
<!ENTITY minscale_zoom25 "<MinScaleDenominator>13</MinScaleDenominator>">
<!ENTITY maxscale_zoom26 "<MaxScaleDenominator>13</MaxScaleDenominator>">
<!ENTITY minscale_zoom26 "<MinScaleDenominator>7</MinScaleDenominator>">
<!ENTITY maxscale_zoom27 "<MaxScaleDenominator>7</MaxScaleDenominator>">
<!ENTITY minscale_zoom27 "<MinScaleDenominator>4</MinScaleDenominator>">
<!ENTITY maxscale_zoom28 "<MaxScaleDenominator>4</MaxScaleDenominator>">
<!ENTITY minscale_zoom28 "<MinScaleDenominator>2</MinScaleDenominator>">
<!ENTITY maxscale_zoom29 "<MaxScaleDenominator>2</MaxScaleDenominator>">
<!ENTITY minscale_zoom29 "<MinScaleDenominator>1</MinScaleDenominator>">
<!ENTITY maxscale_zoom30 "<MaxScaleDenominator>1</MaxScaleDenominator>">
<!ENTITY minscale_zoom30 "<MinScaleDenominator>0.5</MinScaleDenominator>">
<!ENTITY maxscale_zoom31 "<MaxScaleDenominator>0.5</MaxScaleDenominator>">
<!ENTITY minscale_zoom31 "<MinScaleDenominator>0.25</MinScaleDenominator>">
<!ENTITY maxscale_zoom32 "<MaxScaleDenominator>0.25</MaxScaleDenominator>">
<!ENTITY minscale_zoom32 "<MinScaleDenominator>0.125</MinScaleDenominator>">
<!ENTITY maxscale_zoom33 "<MaxScaleDenominator>0.125</MaxScaleDenominator>">
<!ENTITY minscale_zoom33 "<MinScaleDenominator>0.0625</MinScaleDenominator>">
<!ENTITY maxscale_zoom34 "<MaxScaleDenominator>0.0625</MaxScaleDenominator>">
<!ENTITY minscale_zoom34 "<MinScaleDenominator>0.03</MinScaleDenominator>">
<!ENTITY maxscale_zoom35 "<MaxScaleDenominator>0.03</MaxScaleDenominator>">
<!ENTITY minscale_zoom35 "<MinScaleDenominator>0.015</MinScaleDenominator>">
<!ENTITY maxscale_zoom36 "<MaxScaleDenominator>0.015</MaxScaleDenominator>">
<!ENTITY minscale_zoom36 "<MinScaleDenominator>0.007</MinScaleDenominator>">
<!ENTITY maxscale_zoom37 "<MaxScaleDenominator>0.007</MaxScaleDenominator>">
<!ENTITY minscale_zoom37 "<MinScaleDenominator>0.003</MinScaleDenominator>">
<!ENTITY maxscale_zoom38 "<MaxScaleDenominator>0.003</MaxScaleDenominator>">
<!ENTITY minscale_zoom38 "<MinScaleDenominator>0.0015</MinScaleDenominator>">
<!ENTITY maxscale_zoom39 "<MaxScaleDenominator>0.0015</MaxScaleDenominator>">
<!ENTITY minscale_zoom39 "<MinScaleDenominator>0.00075</MinScaleDenominator>">
<!ENTITY maxscale_zoom40 "<MaxScaleDenominator>0.00075</MaxScaleDenominator>">
<!ENTITY minscale_zoom40 "<MinScaleDenominator>0.0003</MinScaleDenominator>">
<!ENTITY maxscale_zoom41 "<MaxScaleDenominator>0.0003</MaxScaleDenominator>">
<!ENTITY minscale_zoom41 "<MinScaleDenominator>0.00015</MinScaleDenominator>">
<!ENTITY maxscale_zoom42 "<MaxScaleDenominator>0.00015</MaxScaleDenominator>">
<!ENTITY minscale_zoom42 "">
